### ISSUE TITLE
建议--Django部署

### ISSUE THREAD

**Issue by Lorryrui** [PyCN/Blog#1]
群主分配的服务器，是有固定外网地址的。楼主有空可以部署在那个上面 这样我们也好直观的看到

**Comment by caitinggui** [comment]
你可以帮忙部署一些吗～

**Comment by Lorryrui** [comment]
下周我看下你这个项目吧。之前只是粗略的看了下。这周刚换工作，可能需要时间缓缓

**Comment by caitinggui** [comment]
已部署于阿里云服务器中，IP为120.24.191.19
